# VBB - Verkehrsverbund Berlin-Brandenburg


> ❗ ACHTUNG - Recherche wurde eingestellt.
>  * Soll-Daten sind bei der VBB im GTFS-Format vorhanden.
>  * Es sind keine Archiv-Daten für die Ermittlung von Verspätungen im ÖPNV ermittelbar.
>  * Die eigenen Sammlung von IST-Daten über den von der VBB angebotenen RT-Feed oder die Rest-Api sind nur Notlösungen.
>  * Im aktuellen Zeitplan ist es nicht möglich representative und ausreichend Daten zu sammeln und diese ggf.durch statistische Hochrechnungen zu erweitern. 
>


**Inhalt:**

1. [Info](#Info)
2. [Datasets](#Datasets)
3. [GTFS](#GTFS)
4. [Test](#Test)



## Info

Die BVG (Berliner Verkehrsbetriebe) ist das Hauptverkehrsunternehmen für U-Bahnen, Busse und Straßenbahnen in Berlin.   
Der VBB (Verkehrsverbund Berlin-Brandenburg) ist die übergeordnete Behörde, die Tarife und Liniennetze in der gesamten Region Berlin-Brandenburg koordiniert.

Der VBB ist bekannt dafür, einen der saubersten GTFS-Datensätze im deutschsprachigen Raum anzubieten.

## Datasets

https://unternehmen.vbb.de/digitale-services/datensaetze/
* ✅ Statische / Schedule data
* ⚠️ Dynamische / Live data / Rest API (Per Email angefragt)
* ⚠️ Real-Time / Live data / Realtime Feed (Test mit Data-Collector)

Weitere, teils redundante, Quellen:
* https://daten.berlin.de/datensaetze?q=vbb
* https://www.opendata-oepnv.de/ht/de/willkommen
* https://mobilithek.info
* https://data.deutschebahn.com/opendata
* https://github.com/orgs/OpenDataVBB/repositories
* https://github.com/derhuerst/record-hafas-data

### Statische Daten (GTFS Downloads)
* Ein "Schnappschuss" des geplanten Angebots (Soll-Zustand).
* Alle Daten lokal, beliebig oft abfragen, ohne Rate-Limits der API zu fürchten, und sie eignen sich perfekt für langfristige Trendanalysen.

### Dynamische Echtzeit-Daten VBB-API (Rest-Schnittstelle)
* Live-Zugriff auf das System (Ist-Zustand + Auskunft).
* Echtzeit-Daten, die nicht in den statischen CSV-Dateien stehen.
* Endpunkte für dein Projekt:
    * departureBoard / arrivalBoard: Was fährt jetzt wirklich ab?
    * journeyPosition: Wo befindet sich ein Fahrzeug gerade exakt? (Perfekt für Live-Visualisierungen).
    * journeyDetail: Verspätungsinformationen und aktuelle Störungen.

### Dynamische Echtzeit-Daten VBB-GTFS-RT (Streaming-Feed)
* Kontinuierlicher Datenstrom: Ein binärer Feed, der den aktuellen "Herzschlag" des gesamten Netzes liefert (Ist-Zustand).
* Effizienz für Big Data: Im Gegensatz zur API-Abfrage einzelner Haltestellen liefert der Feed alle systemweiten Änderungen (Verspätungen, Fahrzeugpositionen) in einem kompakten Paket.
* Perfekt für Machine Learning: Da die Daten direkt über die trip_id mit dem statischen Fahrplan verknüpft sind, lassen sie sich ideal für Vorhersagemodelle und historische Verspätungsarchive nutzen.

* Kern-Komponenten für dein Projekt:
    * TripUpdates: Enthält die aktuellen Zeitabweichungen (Delays) für laufende Fahrten.
    * VehiclePositions: Liefert die GPS-Koordinaten der Fahrzeuge (ideal für Heatmaps der Netzbelastung).
    * ServiceAlerts: Informationen über außerplanmäßige Störungen, Baustellen oder Umleitungen.


### VBB GTFS Realtime Feed

The VBB GTFS Realtime feed can be found at the following URL:   
https://production.gtfsrt.vbb.de/data

You can inspect the feed in a web-based GTFS-RT inspector.   
It is licensed as CC-BY 4.0.
You can fetch it without authentication, up to a limit of 60 requests per minute.
Please make sure to subscribe to the Atom (RSS) feed to get notified about downtime, important changes, etc.
It has CORS enabled, so you can query it from any webpage.
It is served with an ETag header, allowing clients to cache it.
The code behind this is open.


### Daten-Verlgeich

| Feature | Statische GTFS-Daten | VBB-API |
| :--- | :--- | :--- |
| **Fokus** | Planung, Struktur, Geschichte | Echtzeit, Operationen, Live-Status |
| **Datenmenge** | Gigabytes (alle Fahrten des Jahres) | Einzelabfragen (Punktuell) |
| **Analyse-Typ** | Deskriptive Statistik, Graphen | Predictive Analytics (Echtzeit) |
| **Komplexität** | Hoch (SQL/Pandas Handling) | Mittel (JSON Parsing, API-Keys) |

### Rechtliches 

#### Lizenzbeschreibung

Diese Datensätze werden bereitgestellt unter der Lizenz Creative Commons Attribution 4.0 International (CC BY 4.0).

Wenn die Daten der Verkehrsverbund Berlin-Brandenburg GmbH (VBB) Bestandteil des OpenStreetMap-Datenbankwerkes werden, genügt eine Nennung des VBB in der Liste der Beitragenden. Eine Nennung des VBB bei jeder Verwendung der Daten, auch durch Lizenznehmer des oben genannten Datenbankwerks, ist dann nicht mehr erforderlich. Eine indirekte Nennung (Verweis auf Herausgeber des Datenbankwerks, der wiederum auf den VBB verweist) genügt.

#### Haftungsausschluss

Dieser Datenbestand kann Fehler enthalten und/oder unvollständig sein. Der VBB übernimmt keine Haftung und leistet keinerlei Gewähr.

#### Hinweise im Projekt

In deinem Jupyter Notebook / Code: Füge ganz oben oder im Header einen Kommentar ein:  
**Datenquelle: Verkehrsverbund Berlin-Brandenburg GmbH (VBB), bereitgestellt unter CC BY 4.0.**

Auf deiner Karte/Grafik: Schreibe klein an den Rand oder in die Legende:   
**Daten: VBB | Lizenz: CC BY 4.0**

## GTFS
Die General Transit Feed Specification (GTFS) ist ein offener Standard zum Austausch von Fahrplandaten des öffentlichen Verkehrs (ÖPNV) und geografischen Informationen (Haltestellen, Routen). Sie besteht aus Textdateien (.txt) und wird weltweit von Verkehrsbetrieben genutzt, um Daten für Apps wie Google Maps, Apple Maps oder den ÖPNV-Nutzer bereitzustellen. Es gibt zwei Hauptkomponenten: GTFS Static für Fahrpläne und GTFS Realtime für aktuelle Fahrdaten.

Documentations:

* Realtime: https://developers.google.com/transit/gtfs-realtime
* Static: https://developers.google.com/transit/gtfs/reference

* https://gtfs.org/getting-started/what-is-gtfs/
* https://gtfs.org/documentation/overview/


### GTFS Kern-Dateien (Stichwortliste)

| Datei | Kerninhalt | Funktion im Projekt |
| :--- | :--- | :--- |
| **agency.txt** | Verkehrsunternehmen | Identifikation (z.B. BVG vs. S-Bahn) via `agency_id`. |
| **routes.txt** | Linien-Stamm| Name (U7, M41) und Verkehrsmittel-Typ (Bus, Bahn). |
| **trips.txt** | Einzelfahrten | Verknüpft Routen mit Fahrplänen und Linienwegen (Shapes). |
| **stop_times.txt** | Ankunfts-/Abfahrtszeiten | Das Herzstück: Wann hält welcher Trip an welchem Stop? |
| **stops.txt** | Haltestellen | Geokoordinaten (Lat/Lon) und Namen der Stationen. |
| **shapes.txt** | Geometrie | Exakte Linienführung (Polylinien) für die Kartendarstellung. |
| **calendar.txt** | Wochentage | Gültigkeit: Fährt ein Trip Mo-Fr, Sa oder So? |
| **calendar_dates.txt**| Ausnahmen | Feiertage oder Sonderfahrten, die den Kalender überschreiben. |
| **transfers.txt** | Umstiegsinfos | Empfohlene Gehzeiten zwischen Bahnsteigen/Stationen. |

## Test

In [3]:
# IMPORTS

import pandas as pd

In [9]:
# AGENCIES

df_agency = pd.read_csv('./data/vbb/GTFS/agency.txt')

display(df_agency.head(100))

display(df_agency.info())

bvg_id = 796

,agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_phone
0,1,S-Bahn Berlin GmbH,http://www.s-bahn-berlin.de,Europe/Berlin,de,NaN
1,32,Oberhavel Verkehrsgesellschaft mbH,https://www.ovg-online.de,Europe/Berlin,de,NaN
2,47,Verkehrsbetriebe Brandenburg an der Havel GmbH,http://www.vbbr.de,Europe/Berlin,de,NaN
3,84,Stadtverkehrsgesellschaft mbH Frankfurt (Oder),http://www.svf-ffo.de,Europe/Berlin,de,NaN
4,92,Havelbus Verkehrsgesellschaft mbH,http://www.havelbus.de,Europe/Berlin,de,NaN
5,93,Uckermärkische Verkehrsgesellschaft mbH,http://www.wirbewegensie.de,Europe/Berlin,de,NaN
6,108,DB Regio AG,http://www.bahn.de/brandenburg,Europe/Berlin,de,NaN
7,138,Günter Anger Güterverkehrs GmbH & Co. Omnibusv...,http://www.anger-busvermietung.de,Europe/Berlin,de,NaN
8,150,Verkehrsbetrieb Potsdam GmbH,http://www.vip-potsdam.de,Europe/Berlin,de,NaN
9,241,Barnimer Busgesellschaft mbH,http://www.bbg-eberswalde.de,Europe/Berlin,de,NaN
10,246,Verkehrsgesellschaft Teltow-Fläming mbH,http://www.vtf-online.de,Europe/Berlin,de,NaN
11,251,Regionale Verkehrsgesellschaft Dahme-Spreewald...,http://www.rvs-lds.de,Europe/Berlin,de,NaN
12,341,Verkehrsmanagement Elbe-Elster GmbH,http://www.verkehrsmanagement-elbeelster.de,Europe/Berlin,de,NaN
13,346,Verkehrsgesellschaft Oberspreewald-Lausitz mbH,http://www.vgosl.de,Europe/Berlin,de,NaN
14,476,Fritz Behrendt OHG,http://www.behrendt-touristik.de,Europe/Berlin,de,NaN
15,480,Glaser,http://www.busreisen-glaser.de,Europe/Berlin,de,NaN
16,486,Schöneicher Rüdersdorfer Straßenbahn GmbH,http://www.srs-tram.de,Europe/Berlin,de,NaN
17,487,Strausberger Eisenbahn GmbH,http://www.strausberger-eisenbahn.de,Europe/Berlin,de,NaN
18,516,Cottbusverkehr GmbH,http://www.cottbusverkehr.de,Europe/Berlin,de,NaN
19,566,Busverkehr Oder-Spree GmbH,http://www.bos-fw.de,Europe/Berlin,de,NaN
20,596,NEB Betriebsgesellschaft mbH,http://www.neb.de,Europe/Berlin,de,NaN
21,606,A. Reich GmbH Busbetrieb,http://www.a-reich.com,Europe/Berlin,de,NaN
22,706,Sabinchen Touristik GmbH,http://www.vbb.de/de/article/verkehrsunternehm...,Europe/Berlin,de,NaN
23,721,Busverkehr Gerd Schmidt,http://www.fahrschuleschmidt.de,Europe/Berlin,de,NaN
24,726,ORP Ostprignitz-Ruppiner Personennahverkehrsge...,http://www.orp-busse.de,Europe/Berlin,de,NaN
25,731,ODEG Ostdeutsche Eisenbahn GmbH,http://www.odeg.de,Europe/Berlin,de,NaN
26,751,Hanseatische Eisenbahn,http://www.hanseatische-eisenbahn.de,Europe/Berlin,de,NaN
27,772,DB Regio Bus Ost GmbH,https://www.dbregiobus-ost.de,Europe/Berlin,de,NaN
28,781,Lange,http://www.lange-tours.de,Europe/Berlin,de,NaN
29,796,Berliner Verkehrsbetriebe,http://www.bvg.de,Europe/Berlin,de,NaN
30,816,prignitzbus,http://www.prignitz-bus.de,Europe/Berlin,de,NaN
31,841,mobus Märkisch-Oderland Bus GmbH,http://www.mo-bus.de,Europe/Berlin,de,+493341-4494900
32,846,regiobus Potsdam Mittelmark GmbH,http://www.regiobus-pm.de,Europe/Berlin,de,NaN
33,856,Mitteldeutsche Regiobahn,https://www.mitteldeutsche-regiobahn.de/,Europe/Berlin,NaN,NaN
34,996,Betreiber: ecoVista,https://www.ecovista.eu,Europe/Berlin,NaN,+498218090050

<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   agency_id        35 non-null     int64
 1   agency_name      35 non-null     str
 2   agency_url       35 non-null     str
 3   agency_timezone  35 non-null     str
 4   agency_lang      33 non-null     str
 5   agency_phone     2 non-null      str
dtypes: int64(1), str(5)
memory usage: 4.3 KB

None

In [15]:
# ROUTES

df_routes = pd.read_csv('./data/vbb/GTFS/routes.txt')

df_bvg_routes = df_routes[df_routes['agency_id'] == bvg_id].copy()

display(df_bvg_routes.head(100))

display(df_bvg_routes.info())

,route_id,agency_id,route_short_name,route_long_name,route_type,route_color,route_text_color,route_desc
905,28712_700,796,339,NaN,700,NaN,NaN,NaN
906,28260_900,796,21,NaN,900,NaN,NaN,NaN
907,28169_900,796,16,NaN,900,NaN,NaN,NaN
908,27569_700,796,215,NaN,700,NaN,NaN,NaN
909,26782_700,796,N63,NaN,700,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
1000,17466_700,796,N1,NaN,700,NaN,NaN,NaN
1001,17465_700,796,M85,NaN,700,NaN,NaN,NaN
1002,17464_700,796,M82,NaN,700,NaN,NaN,NaN
1003,17463_900,796,M8,NaN,900,NaN,NaN,NaN
1004,17462_700,796,M77,NaN,700,NaN,NaN,NaN

<class 'pandas.DataFrame'>
RangeIndex: 263 entries, 905 to 1167
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   route_id          263 non-null    str
 1   agency_id         263 non-null    int64
 2   route_short_name  263 non-null    str
 3   route_long_name   0 non-null      str
 4   route_type        263 non-null    int64
 5   route_color       9 non-null      str
 6   route_text_color  9 non-null      str
 7   route_desc        0 non-null      str
dtypes: int64(2), str(6)
memory usage: 19.9 KB

None

In [ ]:
# ROUTES

df_routes = pd.read_csv('./data/vbb/GTFS/routes.txt')

df_bvg_routes = df_routes[df_routes['agency_id'] == bvg_id].copy()

display(df_bvg_routes.head(100))

display(df_bvg_routes.info())